#GITHUB ACTIONS TUTORIAL
#name: Go with Gin Framework Backend Tutorial
#
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Grant execute permission for GRADLE
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#      - name: Build & Push Docker Image
#        run:


name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests with Coverage
        run: |
          go test ./... -v -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

#  go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out
#  Create .github/workflows/go.yml:


  //@title Savannah Informatics Mid Level Backend Tests (An Online Market)
  //@version 1.0
  //@description Products, Categories, Customers & Orders
  //@host localhost:8088
  //@BasePath /api/v1
  //@securityDefinitions.oauth2.password OAuth2Password
  //@tokenUrl http://localhost:8080/realms/master/protocol/openid-connect/token
  //@scope profile email
  //@in header